name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x

    - name: Use Yarn latest
      run: |
        npm install -g yarn

    - name: Install dependencies
      run: |
        yarn install

    - name: Run tests
      run: |
        yarn test
