name: Release

on: [release]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      if: github.event.action == published

    - name: echo
      run: |
        echo ${TAG_NAME}
      env:
        TAG_NAME: ${{ github.event.release.tag_name }}
      if: github.event.action == published
