name: Release

on: [release]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      if: github.event.action == 'published'

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
      if: github.event.action == 'published'

    - name: Install dependencies
      run: |
        yarn install
      if: github.event.action == 'published'

    - name: Build
      run: |
        yarn build
      if: github.event.action == 'published'

    - name: Package
      run: |
        NAME=${TAG_NAME} yarn zip
      env:
        TAG_NAME: ${{ github.event.release.tag_name }}
      if: github.event.action == 'published'

    - uses: fnkr/github-action-ghr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GHR_PATH: 'dist/'
      if: github.event.action == 'published'

    - run: ls -la
      if: github.event.action == 'published'
